#!/bin/bash

# Build Diffie-Hellman parameters for the server side
# of an SSL/TLS connection.

source ./vars

if [[ -e $KEY_DIR/dh2048.pem ]];
then
    echo "WARNING: dh2048.pem already exists! Exit."
    exit 1
fi


if [ -d $KEY_DIR ] && [ $KEY_SIZE ]; then
    $OPENSSL dhparam -out ${KEY_DIR}/dh${KEY_SIZE}.pem ${KEY_SIZE}
else
    echo 'Please source the vars script first (i.e. "source ./vars")'
    echo 'Make sure you have edited it to reflect your configuration.'
fi
