#!/bin/bash

# revoke a certificate, regenerate CRL,
# and verify revocation

source ./vars

CRL="crl.pem"
RT="revoke-test.pem"

if [ $# -ne 1 ]; then
    echo "usage: revoke-full <common-name>";
    exit 1
fi

if [ "$KEY_DIR" ]; then
    echo "Revoking OpenVPN certificate: $1"
    cd "$KEY_DIR"
    rm -f "$RT"

    # set defaults
    export KEY_CN=""
    export KEY_OU=""

    # revoke key and generate a new CRL
    $OPENSSL ca -revoke "$1/$1.crt" -config "$KEY_CONFIG"

    echo "."
    # generate a new CRL -- try to be compatible with
    # intermediate PKIs
    $OPENSSL ca -gencrl -out "$CRL" -config "$KEY_CONFIG"
    if [ -e export-ca.crt ]; then
		cat export-ca.crt "$CRL" >"$RT"
    else
		cat ca.crt "$CRL" >"$RT"
    fi
    echo "."
    echo "Verify the revocation:"
    # verify the revocation
    $OPENSSL verify -CAfile "$RT" -crl_check "$1/$1.crt"
    echo "DONE."
else
    echo 'Please source the vars script first (i.e. "source ./vars")'
    echo 'Make sure you have edited it to reflect your configuration.'
fi
