#!/bin/bash

# Sign a certificate signing request (a .csr file)
# with a local root certificate and key.

source ./vars

if [[ -e $KEY_DIR/server.csr ]];
then
    echo "WARNING:server.csr already exists! Exit."
    exit 1
fi

export EASY_RSA="${EASY_RSA:-.}"
"$EASY_RSA/pkitool" --interact --sign $*
